Repository LINE-NOW/LINENOW-ADMIN-Web, pull requests merged in 2024-10, with the labels that each got.

#9 [Feature] #8 - Setting MainWaitingCard filter
  public/images/tag_green.png
  public/images/tag_white.png
  src/apis/domains/booth/_interfaces.ts
  src/apis/domains/booth/apis.ts
  src/hooks/apis/booth.ts
  src/mocks/dummy/waitings.ts
  src/mocks/handlers.ts
  src/pages/main/MainPages.tsx
  src/pages/main/_components/tag/Tag.styled.ts
  src/pages/main/_components/tag/Tag.tsx
  src/pages/main/_components/tag/TagList.tsx
Labels: 🍀 Feature, 🐰 찬주

#11 [Feature] #10 - Setting Auth API
  .gitignore
  index.html
  src/apis/domains/login/_interfaces.ts
  src/apis/domains/login/apis.ts
  src/apis/domains/logout/_interfaces.ts
  src/apis/domains/logout/apis.ts
  src/apis/instance.ts
  src/components/sidebar/Sidebar.tsx
  src/main.tsx
  src/pages/login/LoginPage.tsx
Labels: 🍀 Feature, 🐰 유진

#13 [Feature] #12 - Connecting Waiting Action API
  src/apis/domains/boothManaging/_interfaces.ts
  src/apis/domains/boothManaging/apis.ts
  src/apis/domains/boothManaging/queries.ts
  src/apis/instance.ts
  src/components/modal/modalConfig.tsx
  src/hooks/apis/boothManaging.ts
  src/lib/types/status.ts
  src/mocks/handlers.ts
  src/pages/main/_components/MainWaitingCard.tsx
  src/pages/main/_components/_hooks/useMainWaitingCard.tsx
  src/pages/main/_components/_hooks/useMainWaitingCardModalConfig.ts
Labels: 🍀 Feature, 🐰 서현

#17 [Feature] #14 - Developing Sidebar, Navigation
  mockServiceWorker.js
  public/images/image_vertical_logo.svg
  src/apis/domains/boothManaging/_interfaces.ts
  src/apis/domains/boothManaging/apis.ts
  src/apis/domains/boothManaging/queries.ts
  src/atoms/boothInfo.ts
  src/components/navigation/Navigation.styled.ts
  src/components/navigation/Navigation.tsx
  src/components/sidebar/Sidebar.styled.ts
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarButton.tsx
  src/components/sidebar/useSidebarModalConfig.ts
  src/hooks/apis/boothManaging.ts
  src/hooks/useBoothInfo.ts
  src/lib/interfaces/booth.ts
  src/lib/types/status.ts
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/main/_components/MainWaitingCard.tsx
Labels: 🍀 Feature, 🐰 서현

#19 [Feature] #18 - Setting Auth
  src/App.tsx
  src/apis/domains/booth/apis.ts
  src/apis/domains/boothManaging/apis.ts
  src/apis/domains/login/_interfaces.ts
  src/apis/domains/login/apis.ts
  src/apis/domains/logout/_interfaces.ts
  src/apis/domains/logout/apis.ts
  src/apis/instance.ts
  src/atoms/auth.ts
  src/atoms/boothInfo.ts
  src/atoms/isLoading.ts
  src/components/sidebar/Sidebar.styled.ts
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/useSidebarModalConfig.ts
  src/components/spinner/FullSpinner.tsx
  src/components/spinner/Spinner.styled.ts
  src/components/spinner/Spinner.tsx
  src/hooks/apis/auth.ts
  src/hooks/apis/booth.ts
  src/hooks/apis/boothManaging.ts
  src/hooks/useAuth.ts
  src/hooks/useBoothInfo.ts
  src/hooks/useIsLoading.ts
  src/lib/types/status.ts
  src/main.tsx
  src/mocks/dummy/waitings.ts
  src/mocks/handlers.ts
  src/pages/login/LoginPage.styled.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPages.tsx
  src/pages/main/_components/MainWaitingCard.tsx
  src/pages/main/_components/_hooks/useMainWaitingCard.tsx
  src/routes/GuestRoute.tsx
  src/routes/ProtectedRoute.tsx
  src/routes/router.tsx
Labels: 🍀 Feature, 🐰 서현

#20 [Update] #18 - Updating Linenow package
  package-lock.json
  package.json
Labels: 🐰 서현

#21 [Fix] #18 - Adding Redirects
  public/_redirects
Labels: 🐰 서현

#15 [Feature] #7 - Implement a FAQ
  public/icons/counselor.svg
  public/icons/drop_blue.svg
  public/icons/up_blue.svg
  public/mockServiceWorker.js
  src/constants/faq.ts
  src/pages/faq/FaqPage.styled.ts
  src/pages/faq/FaqPage.tsx
  src/pages/faq/_components/faqOpenChattingCard/FaqOpenChattingCard.styled.ts
  src/pages/faq/_components/faqOpenChattingCard/FaqOpenChattingCard.tsx
  src/pages/faq/_components/faqQuestionList/FaqQuestionList.styled.ts
  src/pages/faq/_components/faqQuestionList/FaqQuestionList.tsx
  src/pages/faq/_components/faqTextCard/FaqTextCard.styled.ts
  src/pages/faq/_components/faqTextCard/FaqTextCard.tsx
  src/pages/faq/_components/index.ts
Labels: 🍀 Feature, 🐰 세호

#23 [Feature] #22 - Developing Mobile View
  index.html
  public/icons/down_white.svg
  public/icons/up_white.svg
  src/App.tsx
  src/apis/domains/booth/_interfaces.ts
  src/components/navigation/Navigation.styled.ts
  src/components/navigation/Navigation.tsx
  src/components/sidebar/Sidebar.styled.ts
  src/components/sidebar/Sidebar.tsx
  src/hooks/apis/auth.ts
  src/hooks/useCountdown.ts
  src/hooks/useView.ts
  src/layouts/DefaultLayout.styled.ts
  src/layouts/DefaultLayout.tsx
  src/lib/interfaces/waiting.ts
  src/mocks/dummy/waitings.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPage.styled.ts
  src/pages/main/MainPages.tsx
  src/pages/main/_components/MainWaitingCard.tsx
  src/pages/main/_components/_hooks/useMainWaitingCard.tsx
  src/pages/main/_components/tag/Tag.styled.ts
  src/styles/local.ts
Labels: 🍀 Feature, 🐰 서현

#25 [Chore] #24 - Fix FAQ
  src/components/navigation/Navigation.tsx
  src/constants/faq.ts
  src/pages/faq/FaqPage.styled.ts
  src/pages/faq/_components/faqOpenChattingCard/FaqOpenChattingCard.tsx
  src/pages/faq/_components/faqQuestionList/FaqQuestionList.styled.ts
Labels: bug, 🐰 찬주

#27 [Fix] #26 - Handling 401 Errors
  src/apis/instance.ts
  src/hooks/apis/auth.ts
Labels: 🍀 Feature, 🐰 서현

#28 [Chore] #16 - Add No Waiting
  src/pages/main/MainPage.styled.ts
  src/pages/main/MainPages.tsx
Labels: documentation, 🐰 찬주

#32 [Feature] #31 - Connecting Waitings Counts API
  package-lock.json
  package.json
  public/mockServiceWorker.js
  src/apis/domains/boothManaging/_interfaces.ts
  src/apis/domains/boothManaging/apis.ts
  src/apis/domains/boothManaging/queries.ts
  src/apis/instance.ts
  src/assets/fonts/Pretendard-Bold.ttf
  src/assets/fonts/Pretendard-Bold.woff
  src/assets/fonts/Pretendard-Medium.ttf
  src/assets/fonts/Pretendard-Medium.woff
  src/assets/fonts/Pretendard-SemiBold.ttf
  src/assets/fonts/Pretendard-SemiBold.woff
  src/assets/fonts/PretendardVariable.woff2
  src/hooks/apis/boothManaging.ts
  src/pages/login/LoginPage.tsx
  src/pages/main/MainPages.tsx
  src/pages/main/_components/tag/TagList.tsx
Labels: 🍀 Feature, 🐰 서현

#34 [Fix] #29 - Fix Error
  index.html
  src/constants/faq.ts
  src/pages/faq/_components/faqQuestionList/FaqQuestionList.styled.ts
  src/pages/main/MainPages.tsx
  src/pages/main/_components/MainWaitingCard.tsx
  src/pages/main/_components/_hooks/useMainWaitingCardModalConfig.ts
  src/styles/local.ts
Labels: bug, 🐰 찬주

#33 [Feature] #30 - Implementing an Onboarding Page
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/useSidebarModalConfig.ts
  src/constants/onboarding.ts
  src/pages/main/MainPages.tsx
  src/pages/onboarding/Onboarding.styled.ts
  src/pages/onboarding/Onboarding.tsx
  src/pages/onboarding/_components/OnboardingModal.tsx
  src/routes/router.tsx
Labels: 🍀 Feature, 🐰 세호

#36 [Fix] #35 - Fix about onboarding
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/useSidebarModalConfig.ts
  src/pages/main/MainPages.tsx
  src/pages/onboarding/Onboarding.tsx
  src/routes/router.tsx
Labels: bug, 🐰 찬주
